version: '3'

services:
  web:
    depends_on:
      - api
    build: ./Web
    image: web
    container_name: web
    ports:
      - "5014:5014"
    networks:
      - client_server
    
  api:
    build: ./Api
    image: api
    container_name: api
    ports:
      - "5000:80"
    networks:
      - client_server

networks:
  client_server:
    driver: bridge