version: '3'

services:
  web:
    depends_on:
      - api
    build: ./Web
    image: web
    container_name: web
    ports:
      - "5014:5014"
    networks:
      - client_server
    
  api:
    depends_on:
      - sqlServer
    build: ./Api
    image: api
    container_name: api
    restart: always
    expose:  
      - "5000:80"
    networks:
      - client_server
      - server_db
    environment:
      - DB_HOST=sqlServer

  sqlServer:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlServer
    environment:
      - SA_PASSWORD=P@ssword123
      - ACCEPT_EULA=Y
    expose:
      - "1433:1433"
    networks:
      - server_db
    volumes:
      - sql_data:/var/opt/mssql 

networks:
  client_server:
    driver: bridge
  server_db:
    driver: bridge

volumes:
  sql_data:
    name: sql_data