name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Conectar ao servidor da 42Labs
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LABS_SERVER_SSH_URL }}
        username: ${{ secrets.LABS_SERVER_SSH_USERNAME }}
        key: ${{ secrets.LABS_SERVER_SSH_PRIVATE_KEY }}
        port: ${{ secrets.LABS_SERVER_SSH_PORT }}
        script: |
          cd DontPanicDaily
          docker-compose down
