name: CD

on:
  workflow_run:
    workflows:
      - ".NET"
    types: 
      - completed

jobs:
  continuous-deployment: 
    runs-on: ubuntu-latest
    steps:
    - name: Conectar ao servidor da 42Labs
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LABS_SERVER_SSH_URL }}
        username: ${{ secrets.LABS_SERVER_SSH_USERNAME }}
        key: ${{ secrets.LABS_SERVER_SSH_PRIVATE_KEY }}
        port: ${{ secrets.LABS_SERVER_SSH_PORT }}
        script: |
          [[ -d dontpanic_live ]] && docker-compose -f dontpanic_live/docker-compose.yml down && rm -rf dontpanic_live
          git clone git@github.com:Labs-ABC/dontpanic_live.git dontpanic_live
          docker-compose -f dontpanic_live/docker-compose.yml up --build -d
